name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: make release

    - name: Test
      run: go test -v ./...

    - name: Remove statik generated file to avoid gofmt failure
      run: rm -f server/public/statik.go

    - name: Check code formatting using gofmt
      uses: Jerome1337/gofmt-action@v1.0.5
